language: go

go:
- tip

install:
- go get -u github.com/golang/dep/cmd/dep
- dep ensure -v

script:
- go test -v ./...
- GOOS=linux GOARCH=arm GOARM=5 go build cmd/smib/smib.go

deploy:
  provider: script
  script: bash deploy.sh
  skip_cleanup: true
  on:
    branch: master