language: go

go:
- tip

install:
- go get github.com/golang/dep/cmd/dep
- dep ensure -v
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls

script:
- go test -v -covermode=count -coverprofile=coverage.out ./...
- $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
- GOOS=linux GOARCH=arm GOARM=5 go build cmd/smib/smib.go

deploy:
  provider: script
  script: bash deploy.sh
  skip_cleanup: true
  on:
    branch: master