language: go

go:
- tip

install:
- go get -u github.com/golang/dep/cmd/dep
- dep install -v

script:
- go test -v ./...
- GOOS=linux GOARCH=arm GOARM=5 go build cmd/smib/smib

deploy:
  provider: script
  script: deploy.sh
  on:
    branch: master